---

variables:
  CONTAINER_REGISTRY_URL: opencast-registry.ctest.univie.ac.at
  BUILDER_IMAGE: whisper-builder
  CONTAINER_REGISTRY_USER: ${NEXUS_USER}
  CONTAINER_REGISTRY_PASS: ${NEXUS_PASS}
  YUM_REPO_URL: opencast-nexus.ctest.univie.ac.at/repository/yum-ustream
  YUM_REPO_USER: ${NEXUS_USER}
  YUM_REPO_PASS: ${NEXUS_PASS}
  BUILD_MODE: static
  RELEASE_VERSION: 6


stages:
  - prepare
  - build


.prepare:
  tags:
    - ags
    - shell
  stage: prepare
  script:
    - cd container
    - podman login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASS $CONTAINER_REGISTRY_URL
    - podman build -t $CONTAINER_REGISTRY_URL/$CONTAINER_NAME -f $CONTAINER_FILE
    - podman push $CONTAINER_REGISTRY_URL/$CONTAINER_NAME
  only:
    - branches

# prepare/builder/debian:
#   extends: .prepare
#   variables:
#     CONTAINER_FILE: Containerfile.builder.debian
#     CONTAINER_NAME: $BUILDER_IMAGE:latest
#   # only:
#   #   changes:
#   #     - container/$CONTAINER_FILE
#   #     - container/scripts/*

prepare/builder/el:
  extends: .prepare
  variables:
    CONTAINER_FILE: Containerfile.builder.$DISTRIBUTION
    CONTAINER_NAME: $BUILDER_IMAGE:$DISTRIBUTION
  parallel:
    matrix:
      - DISTRIBUTION: [el8,el9]
  # only:
  #   changes:
  #     - container/$CONTAINER_FILE


build/whispercpp:
  image: $CONTAINER_REGISTRY_URL/$BUILDER_IMAGE:$DISTRIBUTION
  tags:
    - ags
    - kubernetes
  stage: build
  script:
    - 'dnf -y install openblas-devel atlas-devel'
    - './build-rpm.sh whispercpp'
    - '[[ ${BUILD_MODE} == "static" ]] && echo "Static build: Skip libwhisper library." || ./build-rpm.sh libwhisper'
    - './upload.sh'
  parallel:
    matrix:
      - DISTRIBUTION: [el8,el9]
  artifacts:
    paths:
      - build/*
    expire_in: "30 days"
  only:
    - branches

build/whispercpp-cublas:
  image: $CONTAINER_REGISTRY_URL/$BUILDER_IMAGE:$DISTRIBUTION
  tags:
    - ags
    - kubernetes
  stage: build
  script:
    - 'dnf -y config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel${DISTRIBUTION//[!0-9]/}/x86_64/cuda-rhel${DISTRIBUTION//[!0-9]/}.repo'
    - 'dnf -y module install nvidia-driver:latest-dkms'
    - 'dnf -y install cuda openblas-devel atlas-devel'
    - './build-rpm.sh whispercpp-cublas'
    - '[[ ${BUILD_MODE} == "static" ]] && echo "Static build: Skip libwhisper-cublas library." || ./build-rpm.sh libwhisper-cublas'
    - './upload.sh'
  parallel:
    matrix:
      - DISTRIBUTION: [el8,el9]
  artifacts:
    paths:
      - build/*
    expire_in: "30 days"
  only:
    - branches

build/models:
  image: $CONTAINER_REGISTRY_URL/$BUILDER_IMAGE:$DISTRIBUTION
  tags:
    - ags
    - kubernetes
  stage: build
  script:
    - './build-model.sh ${MODEL_NAME}'
    - './upload.sh'
  parallel:
    matrix:
      - MODEL_NAME: [tiny,base,small,medium,large]
        DISTRIBUTION: [el8,el9]
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH
      when: manual
